"""
STIG Checklist Exporter for vISSM
Exports findings in DISA STIG Viewer compatible format (.ckl)
"""

import os
from typing import Dict, Any
from datetime import datetime
from src.compliance.stig_mapper import STIGMapper
from src.compliance.nist_mapper import NISTMapper


class STIGExporter:
    """Exports vulnerability findings as STIG checklists"""

    def __init__(self):
        self.stig_mapper = STIGMapper()
        self.nist_mapper = NISTMapper()
        self.timestamp = datetime.now().strftime("%Y-%m-%d-%H%M")

    def export_stig_checklist(
        self, analysis_data: Dict[str, Any], output_path: str = None
    ) -> str:
        """Export STIG checklist in CKL format"""
        if not output_path:
            output_path = f"STIG_Checklist_{self.timestamp}.ckl"

        # Ensure output directory exists
        output_dir = os.path.dirname(output_path)
        if output_dir:
            os.makedirs(output_dir, exist_ok=True)

        report = analysis_data.get("report")

        # Collect all plugin IDs and CVEs
        plugin_ids = set()
        cves = []

        if report and hasattr(report, "hosts"):
            for host in report.hosts:
                for vuln in host.vulnerabilities:
                    if vuln.severity >= 2:  # CAT II or higher
                        plugin_ids.add(vuln.plugin_id)
                        if vuln.cve:
                            cves.extend(vuln.cve.split(","))

        # Get STIG findings
        stig_findings = []
        for plugin_id in plugin_ids:
            stig = self.stig_mapper.get_stig_for_plugin(plugin_id)
            if stig:
                stig_findings.append(stig)

        # Generate CKL content
        ckl_content = self._generate_ckl_content(stig_findings)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(ckl_content)

        return output_path

    def _generate_ckl_content(self, findings) -> str:
        """Generate STIG checklist XML content"""
        lines = []
        lines.append('<?xml version="1.0" encoding="UTF-8"?>')
        lines.append("<!--DISA STIG Viewer Checklist File - Generated by vISSM-->")
        lines.append("<CHECKLIST>")

        # Asset information
        lines.append("  <ASSET>")
        lines.append("    <ROLE>None</ROLE>")
        lines.append("    <ASSET_TYPE>Computing</ASSET_TYPE>")
        lines.append("    <HOST_NAME></HOST_NAME>")
        lines.append("    <HOST_IP></HOST_IP>")
        lines.append("    <HOST_MAC></HOST_MAC>")
        lines.append("    <HOST_FQDN></HOST_FQDN>")
        lines.append("    <TECH_AREA></TECH_AREA>")
        lines.append("    <TARGET_KEY>3425</TARGET_KEY>")
        lines.append("    <WEB_OR_DATABASE>false</WEB_OR_DATABASE>")
        lines.append("    <WEB_DB_SITE></WEB_DB_SITE>")
        lines.append("    <WEB_DB_INSTANCE></WEB_DB_INSTANCE>")
        lines.append("  </ASSET>")

        # STIG information
        lines.append("  <STIGS>")
        lines.append("    <iSTIG>")
        lines.append("      <STIG_INFO>")
        lines.append("        <SI_DATA>")
        lines.append("          <SID_NAME>version</SID_NAME>")
        lines.append("          <SID_DATA>1</SID_DATA>")
        lines.append("        </SI_DATA>")
        lines.append("        <SI_DATA>")
        lines.append("          <SID_NAME>releaseinfo</SID_NAME>")
        lines.append(
            f"          <SID_DATA>Generated {datetime.now().strftime('%Y-%m-%d')}</SID_DATA>"
        )
        lines.append("        </SI_DATA>")
        lines.append("        <SI_DATA>")
        lines.append("          <SID_NAME>title</SID_NAME>")
        lines.append("          <SID_DATA>vISSM Automated STIG Checklist</SID_DATA>")
        lines.append("        </SI_DATA>")
        lines.append("      </STIG_INFO>")

        # Vulnerabilities
        for finding in findings:
            lines.append("      <VULN>")
            lines.append("        <STIG_DATA>")
            lines.append("          <VULN_ATTRIBUTE>Vuln_Num</VULN_ATTRIBUTE>")
            lines.append(
                f"          <ATTRIBUTE_DATA>{finding.stig_id}</ATTRIBUTE_DATA>"
            )
            lines.append("        </STIG_DATA>")
            lines.append("        <STIG_DATA>")
            lines.append("          <VULN_ATTRIBUTE>Severity</VULN_ATTRIBUTE>")
            lines.append(
                f"          <ATTRIBUTE_DATA>{finding.severity}</ATTRIBUTE_DATA>"
            )
            lines.append("        </STIG_DATA>")
            lines.append("        <STIG_DATA>")
            lines.append("          <VULN_ATTRIBUTE>Group_Title</VULN_ATTRIBUTE>")
            lines.append(
                f"          <ATTRIBUTE_DATA>{finding.group_title}</ATTRIBUTE_DATA>"
            )
            lines.append("        </STIG_DATA>")
            lines.append("        <STIG_DATA>")
            lines.append("          <VULN_ATTRIBUTE>Rule_ID</VULN_ATTRIBUTE>")
            lines.append(
                f"          <ATTRIBUTE_DATA>{finding.rule_id}</ATTRIBUTE_DATA>"
            )
            lines.append("        </STIG_DATA>")
            lines.append("        <STIG_DATA>")
            lines.append("          <VULN_ATTRIBUTE>Rule_Title</VULN_ATTRIBUTE>")
            lines.append(
                f"          <ATTRIBUTE_DATA>{finding.rule_title}</ATTRIBUTE_DATA>"
            )
            lines.append("        </STIG_DATA>")

            # CCI references
            for cci in finding.cci_refs:
                lines.append("        <STIG_DATA>")
                lines.append("          <VULN_ATTRIBUTE>CCI_REF</VULN_ATTRIBUTE>")
                lines.append(f"          <ATTRIBUTE_DATA>{cci}</ATTRIBUTE_DATA>")
                lines.append("        </STIG_DATA>")

            lines.append("        <STATUS>Open</STATUS>")
            lines.append("        <FINDING_DETAILS>")
            lines.append("Identified via automated Nessus vulnerability scan")
            lines.append("        </FINDING_DETAILS>")
            lines.append("        <COMMENTS></COMMENTS>")
            lines.append("        <SEVERITY_OVERRIDE></SEVERITY_OVERRIDE>")
            lines.append("        <SEVERITY_JUSTIFICATION></SEVERITY_JUSTIFICATION>")
            lines.append("      </VULN>")

        lines.append("    </iSTIG>")
        lines.append("  </STIGS>")
        lines.append("</CHECKLIST>")

        return "\n".join(lines)


def export_stig_checklist(
    analysis_data: Dict[str, Any], output_path: str = None
) -> str:
    """Convenience function to export STIG checklist"""
    exporter = STIGExporter()
    return exporter.export_stig_checklist(analysis_data, output_path)
